import { StyleSheet, Platform } from "react-native";

export const productInfoStyle = StyleSheet.create({
  container: {
    paddingTop: Platform.OS === "android" ? 50 : 60,
    paddingLeft: 10,
    flex: 1,
  },
  navigationView: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 10,
    justifyContent: "space-between",
    paddingRight: 12,
  },
  topText: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 25 : 20,
    color: "#221518",
  },
  productInfoView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#dde5f0c3",
    width: "97%",
    padding: 10,
    overflow: "hidden",
    borderRadius: 20,
  },
  likeBtnView: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingBottom: Platform.OS === "ios" ? 20 : 10,
  },
  likeBtn: {
    backgroundColor: "white",
    width: Platform.OS === "ios" ? 50 : 40,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: Platform.OS === "ios" ? 10 : 5,
    paddingBottom: Platform.OS === "ios" ? 10 : 5,
    borderRadius: 50,
  },
  loaderView: {
    width: "97%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  indicatorView: {
    padding: 10,
    flexDirection: "row",
    display: "flex",
  },
  imageView: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    paddingLeft: Platform.OS === "ios" ? 30 : 20,
    paddingRight: Platform.OS === "ios" ? 30 : 20,
  },
  imageBtnView: {
    flexDirection: "column",
    justifyContent: "center",
    zIndex: 20,
  },
  imgSideBtn: {
    backgroundColor: "white",
    width: Platform.OS === "ios" ? 50 : 40,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: Platform.OS === "ios" ? 10 : 5,
    paddingBottom: Platform.OS === "ios" ? 10 : 5,
    borderRadius: 50,
  },
  productName: {
    fontSize: Platform.OS === "ios" ? 25 : 20,
    width: "97%",
    paddingTop: 10,
    fontFamily: "RobotoCondensed-Bold",
    color: "#221518",
  },
  productAbout: {
    fontFamily: "RobotoCondensed-Regular",
    fontSize: Platform.OS === "ios" ? 18 : 15,
    width: "97%",
    paddingTop: 5,
    color: "#3a3c3fc3",
    textAlign: "justify",
  },
  productRatingView: {
    flexDirection: "row",
    width: "97%",
    justifyContent: "space-between",
  },
  productRating: {
    color: "#3a3c3fc3",
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 18 : 15,
  },
  productPrice: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 25 : 20,
    color: "#E77602",
  },
  productDescription: {
    fontSize: Platform.OS === "ios" ? 25 : 20,
    width: "97%",
    paddingTop: 10,
    fontFamily: "RobotoCondensed-Bold",
    color: "#221518",
  },
  productDescriptionText: {
    fontFamily: "RobotoCondensed-Regular",
    fontSize: Platform.OS === "ios" ? 18 : 15,
    width: "97%",
    paddingTop: 10,
    color: "#3a3c3fc3",
    textAlign: "justify",
    paddingBottom: 10,
  },
  reviewBtnView: {
    position: "absolute",
    right: 15,
    bottom: 100,
  },
  reviewBtn: {
    backgroundColor: "#221518",
    width: 50,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 50,
    paddingHorizontal: 12,
    borderWidth: 0.5,
    borderColor: "white",
  },
  bottomBtnView: {
    paddingBottom: Platform.OS === "ios" ? 30 : 15,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  bottomBtnText: {
    color: "white",
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 18 : 15,
  },
  addToCartBtn: {
    backgroundColor: "#E77602",
    width: "40%",
    alignSelf: "center",
    height: Platform.OS === "android" ? 50 : 60,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: "white",
  },
  checkReviewsBtn: {
    backgroundColor: "#221518",
    width: "40%",
    alignSelf: "center",
    height: Platform.OS === "android" ? 50 : 60,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: "white",
  },
  plusBtnView: {
    flexDirection: "row",
    justifyContent: "flex-end",
    zIndex: 1,
    marginTop: -20,
    marginRight: 10,
  },
  countText: {
    color: "white",
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 18,
  },
});

export const productReviewStyle = StyleSheet.create({
  container: {
    backgroundColor: "#22151840",
    width: "100%",
    height: "100%",
    top: 0,
    position: "absolute",
    justifyContent: "flex-end",
  },
  sheetModal: {
    backgroundColor: "#E77602",
    width: "100%",
    height: "45%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: "hidden",
  },
  sheetModalTopContentView: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 10,
  },
  sheetModalTopContentText: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 17,
    paddingLeft: 10,
    color: "white",
  },
  loadingView: {
    width: "97%",
    height: "82%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 17,
    color: "white",
  },
  reviewContainer: {
    width: "97%",
    alignSelf: "center",
    paddingLeft: 5,
    flexDirection: "column",
    gap: 20,
    overflow: "scroll",
    flexGrow: 1,
  },
  reviewCustomerName: {
    textAlign: "justify",
    color: "white",
    opacity: 0.8,
  },
  reviewReview: {
    textAlign: "justify",
    color: "#3a3c3fc3",
    opacity: 0.9,
    paddingTop: 5,
  },
  reviewDivider: {
    borderBottomWidth: 0.5,
    paddingTop: 5,
    borderColor: "white",
  },
  noReviewContainer: {
    width: "99%",
    height: "85%",
    justifyContent: "center",
    alignItems: "center",
  },
  noReviewText: {
    color: "white",
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 17,
  },
});

export const postReviewStyle = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: 150,
    right: 20,
  },
  textInput: {
    backgroundColor: "white",
    width: 300,
    height: 100,
    borderRadius: 10,
    paddingLeft: 5,
    borderWidth: 1,
    borderColor: "black",
  },
});

export const cartModalStyles = StyleSheet.create({
  container: {
    backgroundColor: "#22151840",
    width: "100%",
    height: "100%",
    top: 0,
    position: "absolute",
    justifyContent: "flex-end",
  },
  sheetModal: {
    backgroundColor: "#FFFFFF",
    width: "100%",
    height: "45%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: "hidden",
  },
  sheetModalTopContentView: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 10,
  },
  sheetModalTopContentText: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 17,
    paddingLeft: 10,
    color: "#E77602",
  },
  cartContainer: {
    width: "97%",
    alignSelf: "center",
    paddingLeft: 5,
    flexDirection: "column",
    gap: 20,
    overflow: "scroll",
    flexGrow: 1,
    paddingBottom: Platform.OS === "ios" ? 20 : 15,
  },
  loadingView: {
    width: "97%",
    height: "82%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 17,
    color: "#E77602",
  },
  noCartContainer: {
    width: "99%",
    height: "85%",
    justifyContent: "center",
    alignItems: "center",
  },
  noCartText: {
    color: "#E77602",
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 17,
  },
  listContainer: {
    backgroundColor: "whitesmoke",
    borderRadius: 15,
    overflow: "hidden",
    flexDirection: "row",
  },
  listImage: {
    width: 120,
    height: 90,
    marginRight: 5,
    borderBottomLeftRadius: 15,
    borderTopLeftRadius: 15,
  },
  listContentContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "65%",
  },
  listContentView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    gap: 5,
  },
  listContentMinusBtn: {
    justifyContent: "center",
    alignItems: "center",
    width: 30,
    height: 30,
    borderRadius: 50,
    backgroundColor: "#F01530",
  },
  listContentPlusBtn: {
    justifyContent: "center",
    alignItems: "center",
    width: 30,
    height: 30,
    borderRadius: 50,
    backgroundColor: "#E77602",
  },
  listContentPrice: {
    fontFamily: "RobotoCondensed-Bold",
    fontSize: Platform.OS === "ios" ? 20 : 18,
    color: "#E77602",
  },
  paymentBtn: {
    backgroundColor: "#34bd34a2",
    width: "95%",
    paddingVertical: Platform.OS === "ios" ? 20 : 15,
    flexDirection: "row",
    justifyContent: "center",
    borderRadius: 10,
    alignSelf: "center",
    marginBottom: 10,
  },
  paymentBtnText: {
    fontFamily: "RobotoCondensed-Bold",
    color: "white",
    fontSize: Platform.OS === "ios" ? 19 : 16,
  },
  productListName: {
    alignSelf: "center",
    fontSize: Platform.OS === "ios" ? 16 : 14,
    fontFamily: "RobotoCondensed-Bold",
  },
});
